<?php
$rows = is_array($list_so) ? $list_so : array();
$bulan = array('Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember');
$toko = $periode = array(); $terbaru = '';
foreach ($rows as $r) {
  $p = !empty($r->periode_ym) ? $r->periode_ym : date('Y-m', strtotime($r->tanggal));
  $toko[(string)$r->id_toko] = $r->nama_toko; $periode[$p] = true;
  if ($p > $terbaru) $terbaru = $p;
}
$namaPeriode = function($p) use ($bulan) {
  return preg_match('/^(\d{4})-(\d{2})$/', $p, $m) ? $bulan[(int)$m[2]-1].' '.$m[1] : '-';
};
?>
<style>
.ha{--primary:#1677b8;--ink:#172033;--muted:#718096;--line:#e6edf5;padding-bottom:30px;color:var(--ink)}
.ha-hero{display:flex;align-items:center;justify-content:space-between;gap:20px;margin-bottom:18px;padding:27px 29px;color:#fff;background:linear-gradient(120deg,#123e68,#1677b8 66%,#25a8ba);border-radius:18px;box-shadow:0 14px 32px rgba(18,83,130,.2)}
.ha-eyebrow{display:block;margin-bottom:6px;color:rgba(255,255,255,.72);font-size:10px;font-weight:700;letter-spacing:.1em;text-transform:uppercase}.ha-hero h1{margin:0 0 5px;font-size:25px;font-weight:700}.ha-hero p{margin:0;color:rgba(255,255,255,.82);font-size:12px}.ha-since{display:flex;align-items:center;gap:10px;padding:10px 13px;background:rgba(255,255,255,.12);border:1px solid rgba(255,255,255,.18);border-radius:11px}.ha-since small,.ha-since strong{display:block}.ha-since small{color:rgba(255,255,255,.7);font-size:9px}.ha-since strong{font-size:11px;white-space:nowrap}
.ha-stat{display:flex;align-items:center;gap:12px;min-height:88px;margin-bottom:16px;padding:16px;background:#fff;border:1px solid var(--line);border-radius:14px}.ha-stat i{display:flex;width:42px;height:42px;align-items:center;justify-content:center;color:var(--c);background:var(--bg);border-radius:11px}.ha-stat strong{display:block;font-size:21px;line-height:1.1}.ha-stat span{color:var(--muted);font-size:10px}
.ha-card{margin-bottom:16px;background:#fff;border:1px solid var(--line);border-radius:16px;box-shadow:0 7px 22px rgba(34,45,70,.05)}.ha-filter{padding:19px 21px}.ha-filter h2,.ha-list-title{margin:0;font-size:14px;font-weight:700}.ha-grid{display:grid;grid-template-columns:1.5fr 1fr 1fr auto;gap:11px;align-items:end;margin-top:14px}.ha-field label{display:block;margin-bottom:6px;color:#526174;font-size:9px;font-weight:700;letter-spacing:.04em;text-transform:uppercase}.ha-control{height:40px;background:#f8fafc;border:1px solid var(--line);border-radius:9px;font-size:11px}.ha-reset{height:40px;padding:0 15px;color:#526174;background:#fff;border:1px solid var(--line);border-radius:9px;font-size:10px;font-weight:700}.ha-reset:hover{color:var(--primary);background:#eff8ff}
.ha-list{overflow:hidden}.ha-list-head{display:flex;align-items:center;justify-content:space-between;padding:18px 21px;border-bottom:1px solid var(--line)}.ha-list-head p{margin:3px 0 0;color:var(--muted);font-size:10px}.ha-count{padding:6px 10px;color:#1769a0;background:#edf7fd;border-radius:999px;font-size:10px;font-weight:700}.ha-table{width:100%;margin:0;font-size:11px}.ha-table thead th{padding:12px;color:#64748b;background:#f8fafc;border:0;border-bottom:1px solid var(--line);font-size:9px;text-transform:uppercase}.ha-table tbody td{padding:13px 12px;vertical-align:middle;border-top:1px solid #f0f3f7}.ha-table tbody tr:hover{background:#fbfdff}.ha-store{display:flex;align-items:center;gap:10px}.ha-store-icon{display:flex;width:38px;height:38px;flex:0 0 38px;align-items:center;justify-content:center;color:var(--primary);background:#edf7fd;border-radius:10px}.ha-store strong,.ha-store small{display:block}.ha-store strong{font-size:12px}.ha-store small{overflow:hidden;max-width:390px;margin-top:3px;color:var(--muted);text-overflow:ellipsis;white-space:nowrap}.ha-period{display:inline-flex;align-items:center;gap:6px;padding:7px 9px;color:#6548b8;background:#f4f1ff;border-radius:8px;font-weight:700;white-space:nowrap}.ha-total{font-size:14px;font-weight:700}.ha-total small{color:var(--muted);font-size:9px}.ha-detail{display:inline-flex;align-items:center;gap:6px;padding:7px 10px;color:#1769a0;background:#edf7fd;border:1px solid #d4eafb;border-radius:8px;font-weight:700;white-space:nowrap}.ha-detail:hover{color:#fff;background:var(--primary)}.ha-empty{display:none;padding:44px 20px;text-align:center;color:var(--muted)}.ha-empty i{display:block;margin-bottom:8px;font-size:24px}.ha-empty strong,.ha-empty span{display:block}.ha-empty strong{color:#475569}.ha-empty span{margin-top:3px;font-size:10px}
.ha-pagination{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:13px 19px;border-top:1px solid var(--line)}.ha-page-info{color:var(--muted);font-size:10px}.ha-page-actions{display:flex;align-items:center;gap:6px}.ha-page-btn{height:34px;padding:0 10px;color:#526174;background:#fff;border:1px solid var(--line);border-radius:8px;font-size:10px;font-weight:700}.ha-page-btn:hover:not(:disabled){color:#fff;background:var(--primary);border-color:var(--primary)}.ha-page-btn:disabled{cursor:not-allowed;opacity:.45}.ha-page-current{height:34px;padding:0 10px;color:#fff;background:var(--primary);border-radius:8px;font-size:10px;font-weight:700;line-height:34px}
@media(max-width:991px){.ha-grid{grid-template-columns:1fr 1fr}.ha-table{min-width:760px}}@media(max-width:575px){.ha-hero{align-items:flex-start;padding:21px;flex-direction:column}.ha-since{width:100%}.ha-grid{grid-template-columns:1fr}.ha-reset{width:100%}.ha-pagination{align-items:flex-start;flex-direction:column}}
</style>
<section class="content ha"><div class="container-fluid">
 <div class="ha-hero"><div><span class="ha-eyebrow"><i class="fas fa-history mr-1"></i> Rekam inventaris</span><h1>Histori Aset Toko</h1><p>Telusuri laporan aset toko berdasarkan nama dan periode pencatatan.</p></div><div class="ha-since"><i class="far fa-calendar-check"></i><div><small>Data tersedia sejak</small><strong>Januari 2025</strong></div></div></div>
 <div class="row">
 <?php $stats=array(array(count($rows),'file-alt','Total laporan','#2563eb','#eff6ff'),array(count($toko),'store','Toko tercatat','#0891b2','#ecfeff'),array(count($periode),'calendar-alt','Periode tersedia','#7c3aed','#f5f3ff'),array($terbaru?$namaPeriode($terbaru):'-','clock','Periode terbaru','#d97706','#fff7ed')); foreach($stats as $s){ ?>
  <div class="col-6 col-lg-3"><div class="ha-stat" style="--c:<?= $s[3] ?>;--bg:<?= $s[4] ?>"><i class="fas fa-<?= $s[1] ?>"></i><div><strong><?= html_escape((string)$s[0]) ?></strong><span><?= $s[2] ?></span></div></div></div>
 <?php } ?></div>
 <div class="ha-card ha-filter"><h2><i class="fas fa-sliders-h mr-2 text-info"></i>Cari dan filter laporan</h2><div class="ha-grid">
  <div class="ha-field"><label for="haSearch">Toko atau alamat</label><input type="search" id="haSearch" class="form-control ha-control" placeholder="Ketik nama toko atau alamat..."></div>
  <div class="ha-field"><label for="haStart">Periode mulai</label><input type="month" id="haStart" min="2025-01" class="form-control ha-control"></div>
  <div class="ha-field"><label for="haEnd">Periode sampai</label><input type="month" id="haEnd" min="2025-01" class="form-control ha-control"></div>
  <button type="button" id="haReset" class="ha-reset"><i class="fas fa-undo-alt mr-1"></i> Reset filter</button>
 </div></div>
 <div class="ha-card ha-list"><div class="ha-list-head"><div><h2 class="ha-list-title">Daftar histori</h2><p>Pilih detail untuk membuka hasil pencatatan pada periode terkait.</p></div><span id="haCount" class="ha-count"><?= count($rows) ?> laporan ditemukan</span></div>
 <div class="table-responsive"><table class="table ha-table"><thead><tr><th class="text-center">No.</th><th>Toko</th><th>Periode</th><th class="text-center">Total aset</th><th class="text-center">Aksi</th></tr></thead><tbody>
 <?php foreach($rows as $i=>$r){$p=!empty($r->periode_ym)?$r->periode_ym:date('Y-m',strtotime($r->tanggal)); ?>
  <tr data-ha-row data-search="<?= html_escape(strtolower($r->nama_toko.' '.$r->alamat)) ?>" data-period="<?= html_escape($p) ?>"><td class="text-center" data-number><?= $i+1 ?></td><td><div class="ha-store"><span class="ha-store-icon"><i class="fas fa-store"></i></span><div><strong><?= html_escape($r->nama_toko) ?></strong><small><i class="fas fa-map-marker-alt mr-1"></i><?= !empty($r->alamat)?html_escape($r->alamat):'Alamat belum tersedia' ?></small></div></div></td><td><span class="ha-period"><i class="far fa-calendar-alt"></i><?= html_escape($namaPeriode($p)) ?></span></td><td class="text-center"><span class="ha-total"><?= number_format((int)$r->total_aset,0,',','.') ?> <small>unit</small></span></td><td class="text-center"><a class="ha-detail" href="<?= base_url('adm/So/detail_aset/'.rawurlencode($r->id_toko).'/'.rawurlencode($p)) ?>"><i class="fas fa-eye"></i> Lihat detail</a></td></tr>
 <?php } ?></tbody></table></div><div id="haEmpty" class="ha-empty"><i class="fas fa-search"></i><strong>Histori tidak ditemukan</strong><span>Ubah nama toko atau rentang periode pencarian.</span></div><div id="haPagination" class="ha-pagination"><span id="haPageInfo" class="ha-page-info"></span><div class="ha-page-actions"><button type="button" id="haPrev" class="ha-page-btn"><i class="fas fa-chevron-left mr-1"></i> Sebelumnya</button><span id="haPageCurrent" class="ha-page-current">1</span><button type="button" id="haNext" class="ha-page-btn">Berikutnya <i class="fas fa-chevron-right ml-1"></i></button></div></div></div>
</div></section>
<script>(function(){var q=document.getElementById('haSearch'),a=document.getElementById('haStart'),b=document.getElementById('haEnd'),rs=document.getElementById('haReset'),empty=document.getElementById('haEmpty'),count=document.getElementById('haCount'),pagination=document.getElementById('haPagination'),info=document.getElementById('haPageInfo'),label=document.getElementById('haPageCurrent'),prev=document.getElementById('haPrev'),next=document.getElementById('haNext'),rows=[].slice.call(document.querySelectorAll('[data-ha-row]')),filtered=[],page=1,size=10;function render(){var total=filtered.length,pages=Math.max(1,Math.ceil(total/size));if(page>pages)page=pages;var first=(page-1)*size,last=Math.min(first+size,total);rows.forEach(function(r){r.style.display='none'});filtered.slice(first,last).forEach(function(r,i){r.style.display='';r.querySelector('[data-number]').textContent=first+i+1});empty.style.display=total?'none':'block';pagination.style.display=total?'flex':'none';count.textContent=total+' laporan ditemukan';info.textContent=total?'Menampilkan '+(first+1)+'–'+last+' dari '+total+' laporan':'';label.textContent=page+' / '+pages;prev.disabled=page<=1;next.disabled=page>=pages}function filter(){var key=(q.value||'').toLowerCase().trim(),from=a.value,to=b.value;filtered=rows.filter(function(r){var p=r.dataset.period;return(!key||r.dataset.search.indexOf(key)>-1)&&(!from||p>=from)&&(!to||p<=to)});page=1;render()}q.addEventListener('input',filter);a.addEventListener('change',filter);b.addEventListener('change',filter);prev.addEventListener('click',function(){if(page>1){page--;render()}});next.addEventListener('click',function(){if(page*size<filtered.length){page++;render()}});rs.addEventListener('click',function(){q.value=a.value=b.value='';filter();q.focus()});filter()})();</script>
